<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-AiDocMngmnt.Worker-87870d08-1091-4dba-86c7-f3e99e40256f</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Azure.AI.Inference" Version="13.4.6-preview.1.26319.6" />
    <PackageReference Include="Aspire.Azure.Messaging.ServiceBus" Version="13.4.6" />
    <PackageReference Include="Aspire.Azure.Storage.Blobs" Version="13.4.6" />
    <PackageReference Include="Aspire.Npgsql.EntityFrameworkCore.PostgreSQL" Version="13.4.6" />
    <PackageReference Include="Microsoft.Extensions.AI" Version="10.8.1" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.10" />
    <PackageReference Include="UglyToad.PdfPig" Version="1.7.0-custom-5" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AiDocMngmnt.ServiceDefaults\AiDocMngmnt.ServiceDefaults.csproj" />
    <ProjectReference Include="..\AiDocMngmnt.Data\AiDocMngmnt.Data.csproj" />
  </ItemGroup>
</Project>
